version: '2.23.3-desktop.2'

services:
  # TODO: Add RabbitMQ
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password123"
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
  apis:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5001
      - 5002:5002
      - 5003:5003
      - 7001:7001
      - 7002:7002
      - 7003:7003
    volumes:
      - .:/pr2
    # environment:
    #   - ConnectionStrings__UsersConnection: "Host=db;Port=5432;Database=PR2AuthServiceUsersDB;Username=postgres;Password=password"
    #   - ConnectionStrings__ConfigsConnection: "Host=db;Port=5432;Database=PR2AuthServiceConfigsDB;Username=postgres;Password=password"
    depends_on:
      - db
  # web:
  #   depends_on:
  #     - apis
volumes:
  postgres: