services:
  db:
    image: postgres:16-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password123"
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
  rmq:
    image: rabbitmq:3-management
    container_name: rmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ""
      RABBITMQ_DEFAULT_PASS: ""
      RABBITMQ_ALLOW_ANONYMOUS: "true"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  apis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apis
    ports:
      - 5001:5001
      - 5002:5002
      - 5003:5003
      - 7001:7001
      - 7002:7002
      - 7003:7003
    volumes:
      - .:/pr2
    depends_on:
      - db
      - rmq
  # TODO: Add WEB

volumes:
  postgres:
  rabbitmq_data: