services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password123"
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  apis:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5001
      - 5002:5002
      - 5003:5003
      - 7001:7001
      - 7002:7002
      - 7003:7003
    volumes:
      - .:/pr2
    depends_on:
      - db
      - rabbitmq
  # TODO: Add WEB

volumes:
  postgres:
  rabbitmq_data: